package com.example.samms.tabs;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.net.URL;

import org.json.JSONArray;
import org.json.JSONObject;

import com.example.samms.SammsUI;
import com.example.samms.windows.WindowsInfo;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container.Filter;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.data.util.filter.SimpleStringFilter;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

/**
 * Tab de Menus
 * @author Juan
 *
 */
public class SAMMSTab6 extends SAMMSTab {

	Table table_Relaciones ;
	
	TextField filter_1;	TextField filter_2;	TextField filter_3;	TextField filter_4;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	public SAMMSTab6(SammsUI sammsUI) {
		super(sammsUI);
//		this.setIcon(new ThemeResource("resources/clock.jpg"));
//		this.setCaption("Clock");
		
		try {
			buildMainLayout();
			fillingTable();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}


	

	private void fillingTable() throws Exception {
		URL val = this.getClass().getResource("./data/intermediariomarket.json");
		BufferedReader buffer = new BufferedReader(new InputStreamReader(new FileInputStream(val.getFile()), "UTF8"));
		String sCadena = "";String sJSON = "";
	    while ((sCadena = buffer.readLine())!=null) {
	    	sJSON = sJSON + sCadena; 
	    }
	    buffer.close();
	    
	    // Creating a JSONObject from a String 
	    JSONObject nodeRoot  = new JSONObject(sJSON); 
	    // Creating a sub-JSONObject from another JSONObject
	    JSONArray nodeArray = nodeRoot.getJSONArray("intermediariomarket");

//	    // Getting the value of a attribute in a JSONObject
//	    String sSDR = nodeStats.getString("sdr");
		//Values
		for (int i = 0; i< nodeArray.length(); i++){
			JSONObject obj = nodeArray.getJSONObject(i);
			table_Relaciones.addItem(new Object[]{obj.get("INTERMEDIARYID"),obj.get("INTERMEDIARYNAME"), obj.get("MARKETID")}, i+1);
		}		
		
		
	}


	@AutoGenerated
	private void buildMainLayout() throws Exception {
		// common part: create layout
		this.setImmediate(true);
		this.setMargin(true);
		this.setWidth("100%");
		this.setHeight("100%");this.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_Relaciones
		table_Relaciones = new Table("");
		table_Relaciones.addStyleName(Reindeer.TABLE_STRONG);
		table_Relaciones.setImmediate(true);
		table_Relaciones.setWidth("820px");
		table_Relaciones.setHeight("100.0%");
		// Define two columns for the built-in container
		table_Relaciones.addContainerProperty("INTERMEDIARYID", String.class, null);
		table_Relaciones.addContainerProperty("INTERMEDIARYNAME", String.class, null);
		table_Relaciones.addContainerProperty("MARKETID", String.class, null);

		// Allow selecting items from the table.
		table_Relaciones.setSelectable(true);
		
		
				
		//ADDDING...................
		this.addComponent(table_Relaciones);
		this.setComponentAlignment(table_Relaciones, Alignment.TOP_LEFT);
		
	}

}
