package com.example.samms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Layout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class SAMMSTabSheetOld extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private TabSheet tabSheet_2;
	@AutoGenerated
	private VerticalLayout tab1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SAMMSTabSheetOld(ComponentContainer mainLayout) {
		// top-level component properties
//		setWidth("100.0%");
//		setHeight("100.0%");
		
		// tabSheet_2
		tabSheet_2 = buildTabSheet_2();
//		((AbsoluteLayout)mainLayout).addComponent(tabSheet_2, "top:30.0px;left:20.0px;");
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}


	@AutoGenerated
	private TabSheet buildTabSheet_2() {
		// common part: create layout
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(false);
		tabSheet_2.setWidth("810px");
		tabSheet_2.setHeight("400px");
		
		// tab1
		tab1 = new VerticalLayout();
		tab1.setImmediate(false);
		tab1.setWidth("-1px");
		tab1.setHeight("-1px");
		tab1.setMargin(false);
		tabSheet_2.addTab(tab1, "Mercury", null);
		
		return tabSheet_2;
	}

}
