package com.example.samms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Tree;

public class Composite1 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label FilterL;
	@AutoGenerated
	private Tree tree_1;
	@AutoGenerated
	private MenuBar menuBar_1;
	@AutoGenerated
	private Table table_Relaciones;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Composite1(ComponentContainer layout) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_Relaciones
		table_Relaciones = new Table();
		table_Relaciones.setCaption("Relaciones");
		table_Relaciones.setImmediate(false);
		table_Relaciones.setWidth("700px");
		table_Relaciones.setHeight("100.0%");
		mainLayout.addComponent(table_Relaciones,
				"top:120.0px;bottom:29.0px;left:140.0px;");
		
		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setImmediate(false);
		menuBar_1.setWidth("-1px");
		menuBar_1.setHeight("-1px");
		mainLayout.addComponent(menuBar_1, "top:20.0px;left:37.0px;");
		
		// tree_1
		tree_1 = new Tree();
		tree_1.setImmediate(false);
		tree_1.setWidth("100px");
		tree_1.setHeight("228px");
		mainLayout.addComponent(tree_1, "top:120.0px;left:20.0px;");
		
		// FilterL
		FilterL = new Label();
		FilterL.setCaption("Filter");
		FilterL.setImmediate(false);
		FilterL.setWidth("140px");
		FilterL.setHeight("-1px");
		FilterL.setValue("Label");
		mainLayout.addComponent(FilterL, "top:42.0px;left:480.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setCaption("Filter");
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		textField_1.setNullSettingAllowed(true);
		mainLayout.addComponent(textField_1, "top:40.0px;left:663.0px;");
		
		return mainLayout;
	}

}
