package com.example.samms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

public class Composite2VertLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_ICN;
	@AutoGenerated
	private Label label_CN;
	@AutoGenerated
	private Label label_IN;
	@AutoGenerated
	private Button button_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Composite2VertLayout(ComponentContainer layout) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("660px");
		mainLayout.setHeight("240px");
		
		// top-level component properties
		setWidth("660px");
		setHeight("240px");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(true);
		button_1.setWidth("120px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:154.0px;left:200.0px;");
		
		// label_IN
		label_IN = new Label("&nbsp;", ContentMode.PREFORMATTED);
		label_IN.setCaption("InsiderNIN");
		label_IN.setImmediate(false);
		label_IN.setWidth("-1px");
		label_IN.setHeight("-1px");
		label_IN.setValue("Label");
		mainLayout.addComponent(label_IN, "top:40.0px;left:40.0px;");
		
		// label_CN
		label_CN = new Label();
		label_CN.setCaption("CompanyNIN");
		label_CN.setImmediate(false);
		label_CN.setWidth("-1px");
		label_CN.setHeight("100.0%");
		label_CN.setValue("Label");
		mainLayout.addComponent(label_CN,
				"top:40.0px;bottom:160.0px;left:220.0px;");
		
		// label_ICN
		label_ICN = new Label();
		label_ICN.setCaption("InsiderCompanyNIN");
		label_ICN.setImmediate(false);
		label_ICN.setWidth("-1px");
		label_ICN.setHeight("100.0%");
		label_ICN.setValue("Label");
		mainLayout.addComponent(label_ICN,
				"top:40.0px;bottom:170.0px;left:380.0px;");
		
		return mainLayout;
	}

}
